# Generated by Django 5.2.1 on 2025-06-04 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('betting', 'Betting'), ('drawing', 'Drawing'), ('showdown', 'Showdown'), ('finished', 'Finished')], default='betting', max_length=20)),
                ('pot', models.IntegerField(default=0)),
                ('current_bet', models.IntegerField(default=10)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('winning_hand', models.CharField(blank=True, max_length=100, null=True)),
                ('can_call', models.BooleanField(default=True)),
                ('can_raise', models.BooleanField(default=True)),
                ('can_fold', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chips', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('folded', 'Folded'), ('all_in', 'All In')], default='active', max_length=20)),
                ('card_count', models.IntegerField(default=5)),
                ('current_bet', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='poker.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField(default=1000)),
                ('has_folded', models.BooleanField(default=False)),
                ('current_bet', models.IntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='poker.game')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades')], max_length=10)),
                ('rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King'), ('A', 'Ace')], max_length=3)),
                ('selected', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='poker.player')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
